version: "3.4"

services:

  nextresearch:
    image: nginx:latest
    ports:
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certificates:/etc/nginx/certificates
      - ./nextresearch.io.conf:/etc/nginx/conf.d/nextresearch.io.conf
      - /var/www/html/:/var/www/html/
      - /var/www/html/artifacts:/var/www/html/artifacts/
